## [作業重點]
清楚了解 L1, L2 的意義與差異為何，並了解 LASSO 與 Ridge 之間的差異與使用情境

## 作業

請閱讀相關文獻，並回答下列問題

[脊回歸 (Ridge Regression)](https://blog.csdn.net/daunxx/article/details/51578787)
[Linear, Ridge, Lasso Regression 本質區別](https://www.zhihu.com/question/38121173)

1. LASSO 回歸可以被用來作為 Feature selection 的工具，請了解 LASSO 模型為什麼可用來作 Feature selection
2. 當自變數 (X) 存在高度共線性時，Ridge Regression 可以處理這樣的問題嗎?


1.  
Ans: 若特徵間存在共線性，則線性回歸的係數會非常大，進而導致對資料的噪音敏感(或可視為模型overfitting & high variance)。Lasso 回歸是在原本線性回歸加入正規化，抑制共線性的特徵參數，若正規係數適當調整後(透過交叉驗證)，可以發現Lasso回歸後某些特徵的係數變成零，相當刪除了與target共線性的特徵(個人猜測)，保留的特徵的代表性就被展現了出來。  
2.  
Ans: 可，原理跟Lasso相同，前提也是需要調整適當的正規化係數。 

In [1]:
import numpy as np

In [2]:
a = np.arange(0, 10)[:, np.newaxis]
a

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [3]:
aa=np.arange(0, 10)

In [4]:
aaa = aa.reshape(-1, 1)
aaa

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [5]:
b = np.arange(1, 6)
b

array([1, 2, 3, 4, 5])

In [7]:
b.shape

(5,)

In [6]:
1 / (aaa + b)

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.5       , 0.33333333, 0.25      , 0.2       , 0.16666667],
       [0.33333333, 0.25      , 0.2       , 0.16666667, 0.14285714],
       [0.25      , 0.2       , 0.16666667, 0.14285714, 0.125     ],
       [0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111],
       [0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ],
       [0.14285714, 0.125     , 0.11111111, 0.1       , 0.09090909],
       [0.125     , 0.11111111, 0.1       , 0.09090909, 0.08333333],
       [0.11111111, 0.1       , 0.09090909, 0.08333333, 0.07692308],
       [0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857]])